server:
  port: 8080
spring:
  application:
    name: study-service-daily
  #数据库相关配置
  datasource:
    druid:
      url: jdbc:mysql://39.101.219.28:3306/study?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: dba
      password: password
      initial-size: 8
      min-idle: 6
      max-active: 16
  # redis相关配置
  redis:
    host: 39.101.219.28
    password: redis
    port: 6379
  # 邮箱配置
  mail:
    host: smtp.aliyun.com
    username: bugfix@aliyun.com
    password: 12241233NIDF
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 39.101.219.28:8848
#mybatis
mybatis:
  # mybatis的数据库映射地址
  mapper-locations: classpath:mapper/*/*Mapper.xml
  # 实体类地址
  type-aliases-package: com.xin.daily.entity
  configuration:
    # 开启驼峰匹配
    map-underscore-to-camel-case: true

